# .gitlab-ci.yml

stages:
  - lint
  - test
  - build
  - push
  - pre-deploy-test
  - deploy
  - post-deploy-test

include:
  - local: ".gitlab-ci/gitlab.yml"
  - local: ".gitlab-ci/dagger.yml"

  # - local: ".gitlab-ci/deploy.yml"
