# .gitlab-ci.yml

stages:
  - test
  - build
  - integration-test

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

test:
  image: ubuntu:latest
  stage: test
  before_script:
    # Install necessary packages
    - apt-get update && apt-get install -y curl
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - source $HOME/.cargo/env
    - uv python install 3.12
  script:
    # Run tests using uv
    - uv run pytest --cov --cov-config=pyproject.toml --cov-report=xml
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - coverage.xml

# Build the Docker image
build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build . -t fastapi-uv:latest --load

# Integration tests
integration-test:
  image: docker:latest
  stage: integration-test
  services:
    - docker:dind
  script:
    - docker run --rm --name fastapi-uv -p 8004:8004 fastapi-uv:latest
    # -
