name: Build and Push (Gitea)

# on: {}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Push container
    # runs-on: ubuntu-latest
    runs-on: macos
    needs: test
    env:
      REGISTRY_GITEA: git.localtest.me

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Log in to GHCR
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_GITEA }}
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # - name: Pull, tag and push test image (docker)
      #   run: |
      #     docker pull alpine:latest
      #     docker tag alpine:latest ${{ env.REGISTRY_GITEA }}/${{ github.actor }}/alpine:latest
      #     docker push ${{ env.REGISTRY_GITEA }}/${{ github.actor }}/alpine:latest

      # - name: Build and Push test image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     file: ./test.dockerfile
      #     push: true
      #     tags: ${{ env.REGISTRY_GITEA }}/${{ github.actor }}/alpine:latest

      - name: Set container image name and tag
        id: vars
        run: |
          IMAGE_NAME=$(echo ${GITHUB_REPOSITORY} | sed "s/${GITHUB_REPOSITORY_OWNER}\///")
          echo "IMAGE_NAME: ${IMAGE_NAME}"

          IMAGE_TAG=$(git describe --tags --abbrev=8 --always | sed 's/-g[0-9a-f]*$//' | sed 's/-\([0-9]*\)$/_\1/')
          echo "IMAGE_TAG = ${IMAGE_TAG}"

          # Save to env vars for later steps
          echo "IMAGE_TAG=${IMAGE_TAG}" >> ${GITHUB_ENV}
          echo "IMAGE_NAME=${IMAGE_NAME}" >> ${GITHUB_ENV}

      # - name: Build and push the container image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: true
      #     tags: |
      #       ${{ env.REGISTRY_GITEA }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      #       ${{ env.REGISTRY_GITEA }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest

      - name: Build and push the container image (docker)
        timeout-minutes: 1
        run: |
          docker build --progress=plain --push \
            -t ${{ env.REGISTRY_GITEA }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            -t ${{ env.REGISTRY_GITEA }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest \
            .
