name: Dagger in GitHub Actions

on:
  push:
    branches: ["main"]
  # pull_request:
  #   types:
  #   - opened
  #   - synchronize
  #   - reopened
  #   - ready_for_review
  # Enable manual trigger for easy debugging
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Hello
        uses: dagger/dagger-for-github@v7
        with:
          module: github.com/shykes/daggerverse/hello
          call: hello --greeting "Ciao" --name "Ugo"
        #   cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Test the app
        uses: dagger/dagger-for-github@v7
        with:
          #   module: .
          call: test --src=.
        #   cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

  build:
    # needs: test
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0

      - name: Set image tag
        id: vars
        run: |
          IMAGE_TAG=$(git describe --tags --abbrev=8 --always | sed 's/-g[0-9a-f]*$//')
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "IMAGE_TAG = ${IMAGE_TAG}"

      - name: Test variables
        run: |
          echo "Username: ${{ github.actor }}"
          echo "Password: ${{ secrets.GITHUB_TOKEN }}"
          echo "User/Org: ${{ github.repository_owner }}"
          echo "Image: ${{ github.event.repository.name }}"
          echo "Tag: ${{ env.IMAGE_TAG }}"

      - name: Build and push the container image
        id: build-push
        uses: dagger/dagger-for-github@v7
        env:
          CR_TOKEN: ${{ secrets.CR_PAT }}
          SHUTUP: 1
        with:
          #   module: .
          call: build-push --registry="ghcr.io" --username="${{ github.actor }}" --password=env:CR_TOKEN --path="${{ github.repository_owner }}" --image="${{ github.event.repository.name }}" --tag="${{ env.IMAGE_TAG }}" --src="."
