name: Dagger in GitHub Actions

on:
  push:
    branches: ["main"]
  # pull_request:
  #   types:
  #   - opened
  #   - synchronize
  #   - reopened
  #   - ready_for_review
  # Enable manual trigger for easy debugging
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  call:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Hello
        uses: dagger/dagger-for-github@v7
        with:
          module: github.com/shykes/daggerverse/hello
          call: hello --greeting Hola --name Jeremy
        #   cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Test
        uses: dagger/dagger-for-github@v7
        with:
          module: .
          call: test --src=.
        #   cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
